version: 2
sources:
  - name: raw
    schema: tiller_project
    description: Tiller raw data from Big Query
    tables:
      - name: order 
        identifier: order_data
        columns:
          - name: id_order
            tests:
              - not_null
              - unique
              
      -  name: order_items
         identifier: order_line

